Feature/#382/advアイテム対応
TUSB/TheUnusualSkyBlock pull request #387
Opened 2024-11-03 09:10 UTC by NePonpon

* `custom_`の接頭語を削除
* `CanDestroy` -> `can_break` : destroyからbreakへ変更
* can_place_onのブロックタグを1.21.1まで更新

2024-11-04 15:11 UTC, sgalsalmon requested changes
data/item/tags/block/can_place_on.json で一部ブロックが抜けているため追記をして欲しい
コメントに抜けているブロックを書いておきます

2024-11-05 00:54 UTC, NePonpon commented
未追加ブロックのコメントが確認できなかった。
もう一度お願いできますか

2024-11-05 03:51 UTC, sgalsalmon requested changes
data/item/tags/block/can_place_on.json で一部ブロックが抜けているため追記をして欲しい

2024-11-05 12:26 UTC, NePonpon commented on data/item/tags/block/can_place_on.json
修正しました。

2024-11-05 12:48 UTC, sgalsalmon approved these changes

2024-11-05 12:52 UTC, merged