Feature/#388/汎用アイテムタグ
TUSB/TheUnusualSkyBlock pull request #389
Opened 2024-11-03 12:50 UTC by NePonpon

* `all`で1.21.1までのアイテムを追加しました。
* `weapons`で中身をアイテムタグに置換しました。
* `weapons`でメイスを追加しました。

2024-11-04 15:25 UTC, sgalsalmon requested changes
data/item/tags/item/all.json で一部アイテムが抜けているため追記をして欲しい
コメントに抜けているブロックを書いておきます

2024-11-05 00:53 UTC, NePonpon commented on data/item/tags/item/all.json
未追加アイテムを見つけてくれてありがとう。
ただ、今は`/clear *`で全アイテム削除を実現できるから削除しちゃってもいい？

2024-11-05 03:59 UTC, sgalsalmon commented on data/item/tags/item/all.json
確かに。削除していいと思います。

2024-11-05 05:51 UTC, NePonpon commented on data/item/tags/item/all.json
`data/item/tags/item/all.json`を削除しました。

2024-11-05 12:42 UTC, merged