json/yml/md コードの空白を統一
TUSB/TheUnusualSkyBlock pull request #648
Opened 2024-12-30 00:54 UTC by waxsd100

## チケットURL

GH-647

## 対応内容・対応背景・妥協点

コードの空白などの整形を実行

## やったこと

* IDEAでコード整形を実行

## レビュー観点

ロジック変更などのコード自体の整形以外のことが発生していないこと

### チェックリスト [(ガイドライン)](https://github.com/orgs/TUSB/discussions/1)
- Pull Request
  - [ ] PRのタイトルはわかり易い名前が設定されていますか?(日本語でも可)
  - [ ] PRの必須項目はすべて記載していますか?
  - [ ] PRの必要ない項目は削除していますか?
  - [ ] PRの内容と変更内容は一致していますか?
    - 1機能=1PRであるべきです。1機能の途中でも問題ありません
- Commit
  - [ ] Commitメッセージはルール通りですか?
    - コミットメッセージの先頭に`[Add|Delete|Modify|Fix|Refactor|Move]`等の動詞の原形を追加してください。([参考](https://www.tam-tam.co.jp/tipsnote/program/post16686.html)) ([参考2](https://note.com/haru_notes/n/n3d9c406e9ac6))
    - コミットメッセージの説明には`GH-〇〇`でチケット番号をつけてください  
      (チケットが存在しない場合は`NO-ISSUE`にしてください
    - マージコミットの場合はこの限りではありません
    
  - [ ] コミットの粒度は適切ですか?
    - 1コミット=1要素(1ロジック)の変更であるべきです  
    
- Branch
  - [ ] ブランチの名前は正しいですか?
    - ブランチ名先頭は`feature/[簡単な説明]` か `fix/[簡単な説明]` の何れかであるべきです
    - 簡単な説明は`英語であるべきです`(不具合発生するので)
  - [ ] ブランチの向き、切り先は正しいですか?

2024-12-30 01:02 UTC, waxsd100 commented
Linterは多分まだ失敗するので無視する

2024-12-30 03:38 UTC, yabane requested changes
.githubのmdファイルで異常な改行によって文章が途切れてしまっています

2024-12-30 06:44 UTC, NePonpon commented on data/area/advancement/system/island_capture.json
1つのcriteriaにつき1行を占めていたのは、シートからの自動生成を貼り付けていたためです。
今後このファイルの変更があったときにこのような整形ルールを適用するか検討する必要があると思います。

2024-12-30 06:53 UTC, NePonpon approved these changes

2025-01-01 22:47 UTC, closed without merging

2025-01-02 13:09 UTC, waxsd100 commented
先にLinter設定を調整すべきなのでクローズ